spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/methods
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8080
