spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/methods
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /moi-swagger.html